website/models.py
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy import ForeignKey
from sqlalchemy.orm import relationship

db = SQLAlchemy(add_models_to_shell=True)


class User(db.Model):
    __tablename__ = "user"
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(100), nullable=False, unique=True)
    username = db.Column(db.String(50), unique=True, nullable=False)
    password = db.Column(db.String, nullable=False)

    def __repr__(self):
        return f"<User: {self.email}>"


class Reservation(db.Model):
    __tablename__ = "reservation"
    id = db.Column(db.Integer, primary_key=True)
    time = db.Column(db.DateTime, nullable=False)
    user_id = db.Column(db.Integer, ForeignKey("user.id"))
    user = relationship("User")

    def __repr__(self):
        return f"<Reservation: {self.time}>"

website/__init__.py
from datetime import datetime
import os
from flask import Flask
from sqlalchemy import select
from werkzeug.security import generate_password_hash


def create_app():
    # create and configure the app
    app = Flask(__name__, instance_relative_config=True)

    app.config.from_object("config.DevConfig")

    # ensure the instance folder exists
    try:
        os.makedirs(app.instance_path)
    except OSError:
        pass

    # Import blueprints
    from .views import views
    from .auth import auth
    from .gym import gym

    app.register_blueprint(views, url_prefix="/")
    app.register_blueprint(auth, url_prefix="/auth")
    app.register_blueprint(gym, url_prefix="/gym")

    from .models import db

    db.init_app(app)

    from .admin import admin, basic_auth, MyAdminIndexView

    admin.init_app(app, index_view=MyAdminIndexView())

    basic_auth.init_app(app)

    @app.shell_context_processor
    def shell_imports():
        return dict(
            select=select,
            generate_password_hash=generate_password_hash,
            datetime=datetime,
        )

    return app

website/auth.py
import functools

from flask import (
    Blueprint,
    flash,
    g,
    redirect,
    render_template,
    request,
    session,
    url_for,
)

from sqlalchemy import select

from werkzeug.security import check_password_hash, generate_password_hash

from website.models import User

from .models import db

from .admin import basic_auth

auth = Blueprint("auth", __name__)


@auth.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "POST":
        # Get form data
        email = request.form.get("email")
        password = request.form.get("password")
        error = None

        # Fetch user
        user = db.session.scalars(select(User).where(User.email == email)).first()

        # Check if user exists
        if user is None:
            error = "Incorrect email."
        elif not check_password_hash(user.password, str(password)):
            error = "Incorrect Password"

        # Add user info to the session
        if error is None:
            session.clear()
            session["user_id"] = user.id
            return redirect(url_for("views.index"))
        else:
            flash(error)

    return render_template("login.html")


@auth.route("/logout")
def logout():
    session.clear()
    return redirect(url_for("views.index"))


@auth.route("/sign-up", methods=["GET", "POST"])
@basic_auth.required  # Only admins can create new users
def sign_up():
    if g.user is not None:
        return redirect(url_for("views.index"))

    if request.method == "POST":
        email = request.form.get("email")
        username = request.form.get("username")
        password = request.form.get("password")
        password_confirm = request.form.get("password-confirm")

        error = None

        user = db.session.scalars(select(User).where(User.email == email)).first()

        if not username:
            error = "Username required."
        elif not password:
            error = "Password required"
        elif not email:
            error = "Email required"
        elif password != password_confirm:
            error = "Passwords don't match"
        elif user is not None:
            error = f"{email} isn't available!"

        user = db.session.scalars(select(User).where(User.username == username)).first()
        if user is not None:
            error = f"{username} isn't available!"

        if error is None:
            user = User(
                email=email,
                username=username,
                password=generate_password_hash(password),
            )
            try:
                db.session.add(user)
                db.session.commit()
            except db.IntegrityError:
                error = f"{email} is already used."
            else:
                flash("User created successfully!")
                return redirect(url_for("auth.login"))

        flash(f"{error}")

    return render_template("sign_up.html")


@auth.before_app_request
def load_logged_in_user():
    user_id = session.get("user_id")

    if user_id is None:
        g.user = None
    else:
        g.user = db.session.scalars(select(User).where(User.id == user_id)).first()


def login_required(view):
    @functools.wraps(view)
    def wrapped_view(**kwargs):
        if g.user is None:
            return redirect(url_for("auth.login"))
        return view(**kwargs)

    return wrapped_view

website/views.py
from flask import Blueprint, redirect, url_for

views = Blueprint("views", __name__)


@views.route("/")
def index():
    return redirect(url_for("gym.planning"))

website/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <link rel="shortcut icon"
              href="{{ url_for('static', filename='favicon.ico') }}">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>
            {% block title %}{% endblock %}
        </title>
        {% block css %}{% endblock %}
    </head>
    <body>
        <header>
            <div class="title">
                <h1>BDS ISMIN</h1>
            </div>
            <div class="links">
                <ul>
                    {% if g.user %}
                        <li>
                            <span>User: {{ g.user['username'] }}</span>
                            <li>
                                <a href="{{ url_for('auth.logout') }}">Log Out</a>
                            {% else %}
                                <li>
                                    <a href="{{ url_for('auth.sign_up') }}">Sign Up</a>
                                    <li>
                                        <a href="{{ url_for('auth.login') }}">Log In</a>
                                    {% endif %}
                                    <li>
                                        <a href="{{ url_for('views.index') }}">Home</a>
                                        <li>
                                            <a href="{{ url_for('gym.planning') }}">Planning Gym</a>
                                        </ul>
                                    </div>
                                </header>
                                <div class="main">
                                    <div class="flash">
                                        {% with messages = get_flashed_messages(with_categories=true) %}
                                            {% if messages %}
                                                {% for message in messages %}
                                                    <div class="message" role="alert">
                                                        {{ message }}
                                                        <button type="button">Dismiss</button>
                                                    </div>
                                                {% endfor %}
                                            {% endif %}
                                        {% endwith %}
                                    </div>
                                    {% block content %}{% endblock %}
                                </div>
                                {% block script %}{% endblock %}
                            </body>
                        </html>

website/templates/calendar.html
{% extends "base.html" %}
{% block title %}
Calendar
{% endblock %}
{% block content %}
{% endblock %}

website/templates/gym_planning.html
{% extends "base.html" %}
{% block css %}
    <link rel="stylesheet"
          href="{{ url_for('static', filename='planning.css') }}">
{% endblock %}
{% block title %}Planning{% endblock %}
{% block content %}
    <h1 id="title">Planning</h1>
    <table id="planning">
        <thead>
            <tr>
                <th>Hours</th>
                {% for day in range(1,8) %}
                    <th>{{ get_date(day) }}</th>
                {% endfor %}
            </tr>
        </thead>
        <tbody>
            {% for hour in range(6,24) %}
                <tr>
                    <th>
                        {{ "{}H - {}H".format(hour,hour+1 if hour+1 < 24 else 0) }}
                    </th>
                    {% for day in range(1,8) %}
                        <td>
                            {% set ns = namespace(must_add_create_btn = True) %}
                            {% for reservation in reservations %}
                                {# check if the reservation belongs to this slot #}
                                {% if reservation.time.isoweekday()== day and
                                    reservation.time.hour == hour and is_same_week(reservation.time)%}
                                    <div class="inner-slot">{{ reservation.user.username }}</div>
                                    {# Reservation is taken so there should not be an add button #}
                                    {% set ns.must_add_create_btn = False %}
                                    {% if g.user == reservation.user %}
                                        <form action="{{ url_for('gym.delete', reservation_id=reservation.id) }}"
                                              method="post">
                                            <input type="submit" value="Cancel">
                                        </form>
                                    {% endif %}
                                {% endif %}
                            {% endfor %}
                            {% if ns.must_add_create_btn %}
                                {% set reservation_time = datetime.fromisocalendar(year,week,day).replace(hour=hour) %}
                                <form action="{{ url_for('gym.create', reservation_time=reservation_time.isoformat(timespec='hours')) }}"
                                      method="post">
                                    <input type="submit" value="+">
                                </form>
                            {% endif %}
                        </td>
                    {% endfor %}
                </tr>
            </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

website/templates/home.html
{% extends "base.html" %}
{% block title %}
BDS
{% endblock %}
{% block content %}
<h1>Welcome!</h1>
{% endblock %}

website/templates/index.html
{% extends "base.html" %}
{% block css %}<link rel="stylesheet" href="{{ url_for('static', filename='index.css') }}">{% endblock %}
{% block title %}BDS{% endblock %}
{% block content %}<h1>Welcome!</h1>{% endblock %}

website/templates/login.html
{% extends "base.html" %}
{% block title %}Login{% endblock %}
{% block content %}
    <form method="POST">
        <fieldset>
            <legend>Login</legend>
            <div class="input-container">
                <label for="email">Email</label>
                <input type="email"
                       id="email"
                       name="email"
                       placeholder="Enter email"
                       required>
            </div>
            <div class="input-container">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <button type="submit" class="submit" value="login">Login</button>
        </fieldset>
    </form>
{% endblock %}

website/templates/sign_up.html
{% extends "base.html" %}
{% block title %}Sign Up{% endblock %}
{% block content %}
    <form method="POST">
        <fieldset>
            <legend>Sign Up</legend>
            <div class="input-container">
                <label for="email">Email</label>
                <input type="email"
                       id="email"
                       name="email"
                       placeholder="Enter email"
                       required>
            </div>
            <div class="input-container">
                <label for="username">Username</label>
                <input type="text" id="username" name="username" placeholder="Jean" required>
            </div>
            <div class="input-container">
                <label for="password">Password</label>
                <input type="password" id="password" name="password" required>
            </div>
            <div class="input-container">
                <label for="password-confirm">Password (Confirm)</label>
                <input type="password"
                       id="password-confirm"
                       name="password-confirm"
                       required>
            </div>
            <button type="submit" class="submit" value="sign_up">Sign Up</button>
        </fieldset>
    </form>
{% endblock %}